export const site = {
  name: "MindCare Health",
  tagline: "Personalized Mental Healthcare",
  logo: "/images/logo.png",
  favicon: "/images/favicon.png",
  phone: "(555) 214-8900",
  phoneHref: "tel:+15552148900",
  email: "hello@mindcarehealth.com",
  emailHref: "mailto:hello@mindcarehealth.com",
  address: "428 Wellness Avenue, Suite 200",
  city: "Austin, TX 78701",
  hours: [
    { day: "Monday – Friday", time: "8:00 AM – 7:00 PM" },
    { day: "Saturday", time: "9:00 AM – 2:00 PM" },
    { day: "Sunday", time: "Closed" },
  ],
  routes: {
    book: "/#book-meeting",
    bookConsult: "/#book-meeting",
    inquiry: "/#contact",
    specialists: "/#specialists",
    services: "/#services",
    about: "/#about",
    approach: "/#approach",
    testimonials: "/#testimonials",
    faq: "/#faq",
    contact: "/#contact",
  },
  social: {
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
    facebook: "https://facebook.com",
  },
  images: {
    hero: "/images/hero.png",
    whyChoose: "/images/why-mindcare.png",
    approach: "/images/approach.png",
    specialists: [
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=800&q=80",
    ],
  },
} as const;
